#The plugin now supports 2 types of 2fa: standard (Google Authenticator) based 2fa,
#as well as the Yubikey.

#'2fa'- "Google Authenticator" type 2fa
#'yubikey' - Yubikey based authentication

#To enable/disable each type of authentication, simply comment/uncomment each line
#in question
authenticators:
- "2fa"
#- "yubikey"

#Yubikey configuration: Only needs to be filled in if you are using yubikey auth
yubikey:
  clientId: -1 #Your client id
  clientSecret: secret #Your client secret

#2fa configuration: Only needs to be filled in if you are using 2fa auth
2fa:
  #This is the key that will be by default displayed in the user's authentication
  #app. This may be whatever you want, but we suggest making it your server name
  #or some other identifier.
  serverIp: "mc.myserver.com"

#If this option is true, the plugin will not factor into account the last IP of the player, and will force the player to
#log in each time they are authenticated
forceSameIPAuthentication: false

#If this option is false, the plugin will not tamper with the player inventory, and all authentication will be chat based.
#If this option is true, the plugin will stash away the player inventory and display the QR code in a map.
#Leaving this option at true is recommended but may conflict with other inventory manager plugins.
inventoryTampering: true

#Sets the bungee configuration parameters. If bungee is enabled, players will only need to authenticate once on one of
#servers
bungee:
  # Whether bungee mode is enabled. Plugin must be on bungee server with same channel
  enabled: false
  # Channel to send messages over. Must be same on Bungee
  channel: "mcauthenticator:auth"

dataBacking:
# This plugin supports 3 independant datastorage mechanisms. At the current time, there is no way to convert between the
# two, however, this may be added in the future.

  #Types:
  # - single: Saves all data in one single file. Good for most installations
  # - directory: Saves each player in their own file within a directory
  # - mysql: Saves each player's data within a mysql database
  type: single

  #If type is single, this specifies which file to save it in.
  file: "playerData.json"

  #If type is directory, this specifies which directory to save the data in.
  directory: "playerData"

  #If type is mysql, this specifies login details
  mysql:
    url: "jdbc:mysql://localhost:3306/db"
    username: "test"
    password: "test"
    queryTimeout: 5

#Messages section. Each message uses standard '&' color codes.
#A message can be split into multiple lines using the \n character.
messages:
  prefix: "&8[&4Auth&8] "

  #Displayed in normal use
  authenticationPrompt: "&4This account has 2FA enabled on it. Please enter your authentication code."
  ipPreAuthenticated: "&7You are already authenticated since your IP matched your last log in IP."

  notAuthed: "&4You are not authenticated! Please enter your 2FA code."
  authenticated: "&7You have been authenticated"
  authFailed: "&4That was not a valid code. You are not yet authenticated."


  #Displayed after successful commands

  selfDisabled: "&cYou have disabled 2FA on your account."
  selfReset: "&cYou have reset 2FA on your account. Please enter the code shown on your device from the new code."

  #Other Success
  otherEnable: "&4%player%&c has enabled 2FA on your account!"
  otherDisable: "&4%player%&c has disabled 2FA on your account!"
  otherReset: "&4%player%&c has reset the 2FA on your account!\n &4Please enter the code generated by the app from the QR code."

  #Command errors
  alreadyEnabled: "&cYou already have 2FA enabled!"
  alreadyDisabled: "&cYou already have 2FA disabled!"
  disableForced: "&cYou are not permitted to disable 2FA on your account!"
  resetDisabled: "&cYour account has 2FA disabled."
  resetNotAuthed: "&cYou cannot reset your account until you authenticate!"
  resetForced: "&cYou are not permitted to reset 2FA on your account!"

  #Gauth specific messages
  sendAuthCode: "&7This server has 2FA support enabled. Your temporary code is\n&7%code%\n&7which is also viewable at\n&8%url%\n&7To use 2FA, enter the code generated by your device:"

  #Yubikey specific messages
  yubikeyInitPrompt: "&7This server has Yubikey support enabled for your 2FA! You may set up 2FA for this account by pressing your yubikey in the chat box:"
