name: MCAuthenticator
main: io.ibj.mcauthenticator.MCAuthenticator
version: ${project.version}
authors: ['Joseph Hirschfeld <joe@ibj.io>','aaomidi']
description: "Provides 2FA ability to minecraft servers"

commands:
  auth:
    description: Command to MCAuthenticator commands
    aliases: ["2fa", "authenticator", "mcauthenticator"]

permissions:
  mcauthenticator.enable:
    default: op
  mcauthenticator.disable:
    default: op
  mcauthenticator.enable.other:
    default: false #Only allow console by default
  mcauthenticator.disable.other:
    default: false
  mcauthenticator.lock:
    default: op
  mcauthenticator.use:
    default: op
  mcauthenticator.reload:
    default: false #Only allow console by default
  mcauthenticator.reset:
    default: op
  mcauthenticator.reset.other:
    default: false #Only allow console by default